2023-02-25 19:57:49,536 INFO    MainThread:19656 [wandb_setup.py:_flush():68] Configure stats pid to 19656
2023-02-25 19:57:49,537 INFO    MainThread:19656 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\.config\wandb\settings
2023-02-25 19:57:49,537 INFO    MainThread:19656 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\CS6910\Assignment 1\wandb\settings
2023-02-25 19:57:49,538 INFO    MainThread:19656 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-25 19:57:49,538 INFO    MainThread:19656 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-25 19:57:49,539 INFO    MainThread:19656 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230225_195749-ptf2nm3b\logs\debug.log
2023-02-25 19:57:49,539 INFO    MainThread:19656 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230225_195749-ptf2nm3b\logs\debug-internal.log
2023-02-25 19:57:49,540 INFO    MainThread:19656 [wandb_init.py:init():532] calling init triggers
2023-02-25 19:57:49,540 INFO    MainThread:19656 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-02-25 19:57:49,540 INFO    MainThread:19656 [wandb_init.py:init():554] re-initializing run, found existing run on stack: 8ypstigs
2023-02-25 19:57:49,542 INFO    MainThread:19656 [wandb_run.py:_finish():1854] finishing run ananthu2014/ED22S015_DL/8ypstigs
2023-02-25 19:57:49,542 INFO    MainThread:19656 [jupyter.py:save_history():449] not saving jupyter history
2023-02-25 19:57:49,543 INFO    MainThread:19656 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-02-25 19:57:49,543 INFO    MainThread:19656 [wandb_init.py:_jupyter_teardown():420] cleaning up jupyter logic
2023-02-25 19:57:49,543 INFO    MainThread:19656 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-02-25 19:57:49,544 INFO    MainThread:19656 [wandb_run.py:_restore():2066] restore
2023-02-25 19:57:49,544 INFO    MainThread:19656 [wandb_run.py:_restore():2072] restore done
2023-02-25 19:57:54,879 INFO    MainThread:19656 [wandb_run.py:_footer_history_summary_info():3442] rendering history
2023-02-25 19:57:54,879 INFO    MainThread:19656 [wandb_run.py:_footer_history_summary_info():3474] rendering summary
2023-02-25 19:57:54,885 INFO    MainThread:19656 [wandb_run.py:_footer_sync_info():3398] logging synced files
2023-02-25 19:57:54,892 INFO    MainThread:19656 [wandb_init.py:init():588] starting backend
2023-02-25 19:57:54,892 INFO    MainThread:19656 [wandb_init.py:init():592] setting up manager
2023-02-25 19:57:54,896 INFO    MainThread:19656 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-02-25 19:57:54,912 INFO    MainThread:19656 [wandb_init.py:init():599] backend started and connected
2023-02-25 19:57:54,935 INFO    MainThread:19656 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-02-25 19:57:54,935 INFO    MainThread:19656 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-02-25 19:57:54,935 INFO    MainThread:19656 [wandb_init.py:init():687] updated telemetry
2023-02-25 19:57:55,004 INFO    MainThread:19656 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-02-25 19:57:58,893 WARNING MsgRouterThr:19656 [router.py:message_loop():77] message_loop has been closed
2023-02-25 19:58:00,075 ERROR   MainThread:19656 [wandb_init.py:init():1160] error
Traceback (most recent call last):
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 1133, in init
    run = wi.init()
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 730, in init
    result = run_init_handle.wait(
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 271, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
